// RootLayout.server.tsx
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "F4Fish",
  description: "Generated by create next app",
};

export default function RootLayoutServer({ children }: { children: React.ReactNode }) {
  return <>{children}</>; // You can include other server-side logic here if needed
}
